### PR TITLE
fix: Make react a peer dependency

### PR DESCRIPTION
**Pull request by marcel-casavo**
## Why
to avoid multiple react versions in the consumer

### CODE REVIEW

**Comment by moebiusmania** [comment]
@marcel-casavo just 2 notes on the PR itself:

- shorter PR name
- fill the part of the template that you need istead of leaving as-is
- add the typology label (chromatic wasn't required for this issue, but that not important)

**Comment by moebiusmania** [comment]
tested locally with `run dev` and the `build`s command and LGTM 🚀

**Comment by marcel-casavo** [comment]
Thanks @moebiusmania, good points, thanks for the updates you did. 
The draft PR was empty because the objective was only to test the CI in regards to a potential chromatic deploy to see if everything works as expected.

**Comment by marcel-casavo** [comment]
@moebiusmania  @pietrograndi  I reverted the `package.json` version bump as if I'm not wrong it's supposed to be in the commit that does the new release.

**Comment by moebiusmania** [comment]
@marcel-casavo it was correct 😄 no need to have another PR just to bump the package, just reset to the prvious one and force push

**Pull request merged**
